version: '3'

services:
  myapp:
    container_name: myapp
    restart: always
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./myapp:/opt/myapp
    environment:
      - NODE_ENV=production
      - REDISCLOUD_URL=redis://localhost:63799
    links:
      - redis
  redis:
    container_name: myapp-redis
    image: 'redis:4.0.11'
    ports:
      - '63799:6379'

#   traefik:
#     image: traefik:1.3.6-alpine
#     ports:
#       - "8081:8081"
#     volumes:
#     - ./traefik/traefik.toml:/traefik.toml
#     command: "--file"
#     networks:
#       - proxy

# networks:
#   proxy:
#     external: false
